title: Marcos Bellucci
email: delbetu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website to show who am i and how i work.
baseurl: "" # the subpath of your site
url: "https://delbetu.github.io"
twitter_username: delbetu
github_username:  delbetu

plugins:
  - jemoji
  - jekyll-sitemap


# Build settings
markdown: kramdown
