title: Marcos Bellucci
email: MarcosBellucci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website to show who am i and how i work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delbetu.github.io"
twitter_username: delbetu
github_username:  delbetu
plugins:
  - jemoji

# Build settings
markdown: kramdown
